### ISSUE TITLE
20348 SDK fails to download

### ISSUE THREAD

**Issue by jackknobel** [GuillaumeFalourd/setup-windows10-sdk-action#3]
Heya!

This is a fantastic little action, thank you so much for getting it up and running.
However I am bumping into an issue where I'd like to use the preview 2104 SDK but unfortunately the action seems to fail in getting it with the following error:
```
WARNING: Failed to fetch updated file from 
https://software-download.microsoft.com/download/sg/Windows_InsiderPreview_SDK_en-us_20348_1.iso : Exception calling 
"DownloadFile" with "2" argument(s): "The remote server returned an error: (400) Bad Request."
10 retries left, trying download again
```

I'm using the following within the action:
```
with:
    sdk-version: 20348
```
The SDK is listed and available here: https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/.

If you need any more information, please do let me know!

Thanks heaps,
Jack

**Comment by GuillaumeFalourd** [comment]
Hi @jackknobel , how are you doing? 😄 

Thank you for the feedback and for opening this issue!

I checked here and the problem seems to be related to the powershell script used to install the windows SDK.

This script has been exported from the [WindowsCommunityToolkit repository](https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/main/build/Install-WindowsSdkISO.ps1) and I'm not familiar with it.

I'll use import the updated one on the `dev` branch and you'll be able to check it using:

```
- uses: GuillaumeFalourd/setup-windows10-sdk-action@dev
  with:
    sdk-version: 20348
```

Let's see if it can resolve the problem or if we would need to update another part of the action.

**Comment by GuillaumeFalourd** [comment]
It seems like the error persists even with the latest powershell script version ([workflow run](https://github.com/GuillaumeFalourd/setup-windows10-sdk-action/runs/3262232881?check_suite_focus=true)).

I guess the URL format has been modified for newest SDK versions and the script on the WindowsCommunityToolkit repo hasn't been updated yet.

Could be interesting opening an ISSUE there as well for investigation, what do you think @jackknobel ?

**Comment by jackknobel** [comment]
Definitely a good idea, from my quick investigation the powershell script has the hardcoded URL:
https://software-download.microsoft.com/download/sg/Windows_InsiderPreview_SDK_en-us_$($buildNumber)_1.iso

But the 20348 SDK points to is:
https://software-download.microsoft.com/download/sg/20348.1.210507-1500.fe_release_WindowsSDK.iso

Having said that the 19041 SDK lives here:
https://software-download.microsoft.com/download/pr/19041.685.201201-2105.vb_release_svc_prod1_WindowsSDK.iso

So I dont even know if the powershell script pulls the final SDK's :/.

Either way, looking over the powershell script itself the only "easy" solution I can think of is to add an optional custom url parameter.
Do you think that would make sense?

**Comment by xiaozhuai** [comment]
> Hi @jackknobel , how are you doing? 😄
> 
> Thank you for the feedback and for opening this issue!
> 
> I checked here and the problem seems to be related to the powershell script used to install the windows SDK.
> 
> This script has been exported from the [WindowsCommunityToolkit repository](https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/main/build/Install-WindowsSdkISO.ps1) and I'm not familiar with it.
> 
> I'll import the [updated one](https://github.com/CommunityToolkit/WindowsCommunityToolkit/commits/main/build/Install-WindowsSdkISO.ps1) on the `dev` branch and you'll be able to check it using:
> 
> ```
> - uses: GuillaumeFalourd/setup-windows10-sdk-action@dev
>   with:
>     sdk-version: 20348
> ```
> 
> Let's see if it can resolve the problem or if we would need to update another part of the action.

@GuillaumeFalourd 
I tried use dev branch with no luck. Will it be fixed?

```
Installing Windows 10 SDK version 10.0.20348.0
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_actions\GuillaumeFalourd\setup-windows10-sdk-action\dev\externals\install-winsdk.ps1' 20348"
Checking for installed Windows SDK 10.0.20348.0...Installation required
Checking if StrongName bypass required...REQUIRED
Downloading winsdk_20348.iso...
WARNING: Failed to fetch updated file from
https://software-download.microsoft.com/download/sg/Windows_InsiderPreview_SDK_en-us_20348_1.iso
winsdk_20348.iso was not found at C:\Users\RUNNER~1\AppData\Local\Temp\WindowsSDK\winsdk_20348.iso
At D:\a\_actions\GuillaumeFalourd\setup-windows10-sdk-action\dev\externals\install-winsdk.ps1:36 char:13
+ throw "$downloadName was not found at $downloadDest"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OperationStopped: (winsdk_20348.is...insdk_20348.iso:String) [], RuntimeException
+ FullyQualifiedErrorId : winsdk_20348.iso was not found at C:\Users\RUNNER~1\AppData\Local\Temp\WindowsSDK\winsdk
_20348.iso
Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
Cleaning up orphan processes
```

**Comment by GuillaumeFalourd** [comment]
Hi @xiaozhuai , how are you doing?

As I said above:

> It seems like the error persists even with the latest powershell script version ([workflow run](https://github.com/GuillaumeFalourd/setup-windows10-sdk-action/runs/3262232881?check_suite_focus=true)).
I guess the URL format has been modified for newest SDK versions and the script on the WindowsCommunityToolkit repo hasn't been updated yet.

A solution could be to update the powershell script itself, and as @jackknobel explained, the only "easy" solution could be to add an optional custom url parameter to download the correct SDK version.

As this powershell script has been exported from the [WindowsCommunityToolkit repository](https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/main/build/Install-WindowsSdkISO.ps1) and I'm not familiar with it (neither with powershell), I didn't check it yet. I would be happy to have some support to correct this issue 😸

**Comment by GuillaumeFalourd** [comment]
I have updated the powershell script with the hardcoded URL for the 20348 SDK version on the `dev` branch.

[It seems to work as expected on the workflow run I used for test.](https://github.com/GuillaumeFalourd/setup-windows10-sdk-action/runs/6063000227?check_suite_focus=true)

Could someone try again using the action as below:

```yaml
- uses: GuillaumeFalourd/setup-windows10-sdk-action@dev
  with:
    sdk-version: 20348
```

And give me a feedback so that I create a new release version for the action? 😄

**Comment by xiaozhuai** [comment]
> I have updated the powershell script with the hardcoded URL for the 20348 SDK version on the `dev` branch.
> 
> [It seems to work as expected on the workflow run I used for test.](https://github.com/GuillaumeFalourd/setup-windows10-sdk-action/runs/6063000227?check_suite_focus=true)
> 
> Could someone try again using the action as below:
> 
> ```yaml
> - uses: GuillaumeFalourd/setup-windows10-sdk-action@dev
>   with:
>     sdk-version: 20348
> ```
> 
> And give me a feedback so that I create a new release version for the action? 😄

@GuillaumeFalourd Thanks! I've tried it and it works like a charm now!

```
Run GuillaumeFalourd/setup-windows10-sdk-action@dev
Installing Windows 10 SDK version 10.0.203[4](https://github.com/xiaozhuai/angle_builds/runs/6073908578?check_suite_focus=true#step:2:4)[8](https://github.com/xiaozhuai/angle_builds/runs/6073908578?check_suite_focus=true#step:2:8).0
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_actions\GuillaumeFalourd\setup-windows[10](https://github.com/xiaozhuai/angle_builds/runs/6073908578?check_suite_focus=true#step:2:10)-sdk-action\dev\externals\install-winsdk.ps1' 20348"
Checking for installed Windows SDK 10.0.20348.0...Installation required
Checking if StrongName bypass required...REQUIRED
Downloading winsdk_20348.iso...Done
Mounting ISO winsdk_20348.iso...Done
Installing WinSDK...Done
Dismounting ISO winsdk_20348.iso...Done
Disabling StrongName for Windows SDK...Done
```

**Comment by GuillaumeFalourd** [comment]
Great! I'll generate the `v1.3` release version.
Closed by: https://github.com/GuillaumeFalourd/setup-windows10-sdk-action/pull/7
