### ISSUE TITLE
Add support for latest windows sdk: 10.0.22000.0

### ISSUE THREAD

**Issue by niemyjski** [GuillaumeFalourd/setup-windows10-sdk-action#9]
I noticed the powershell script currently doesn't handle the latest windows sdk, can this please be updated or add a download url option

**Comment by GuillaumeFalourd** [comment]
Hi @niemyjski, thank you for opening this issue!
That's a great idea! I'll work on it asap 👍🏼 
Do you happen to know in which URL to download the `22000` SDK version `.iso` file?

**Comment by GuillaumeFalourd** [comment]
Found it:
https://software-static.download.prss.microsoft.com/pr/download/22000.194.210911-1543.co_release_svc_prod1_WindowsSDK

**Comment by GuillaumeFalourd** [comment]
New release v1.5 generated successfully: https://github.com/GuillaumeFalourd/setup-windows10-sdk-action/releases/tag/v1.5

Has been tested successfully for SDK 22000 [here](https://github.com/GuillaumeFalourd/setup-windows10-sdk-action/actions/runs/2257727861)
